name: Deploy Multiple mdBooks
on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book_dir: [doc/workflow]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        run: |
          cd ${{ matrix.book_dir }}
          mdbook build

      # Step to move index.html from /doc/ to site root
      - name: Deploy Landing Page to Root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc  # Source folder where index.html lives
          # No destination_dir means files are placed at the root of gh-pages
          keep_files: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.book_dir }}/book
          destination_dir: ${{ matrix.book_dir }}
          keep_files: true
